name: zone_di2
version: 2.0.0
homepage: https://github.com/pschiffmann/zone_di.dart
description: Dependency injection with a functional API that works without code generation, mirrors or passing around Injector objects.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  meta: ^1.1.7
dev_dependencies: 
  lint_hard: ^1.0.2
  test: ^1.6.7
