name: di_zone2
version: 1.0.2
homepage: https://github.com/noojee/scope
documentation: http://scope.noojee.dev
description: Dependency injection for Dart
repository: https://github.com/noojee/scope
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  meta: ^1.1.7
dev_dependencies: 
  lint_hard: ^1.0.2
  test: ^1.6.7
