name: scope
version: 1.0.0
homepage: https://github.com/noojee/scope
description: Dependency injection for Dart
documentation: scope.noojee.dev
repository: https://github.com/noojee/scope
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  meta: ^1.1.7
dev_dependencies: 
  lint_hard: ^1.0.2
  test: ^1.6.7
