name: scope
version: 5.0.0
homepage: https://github.com/onepub-dev/scope
documentation: https://scope.onepub.dev
description: A Dependency injection (Inversion of Control) library. Supports nested Scopes and multiple values of the same type.
repository: https://github.com/onepub-dev/scope
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ^1.1.7
dev_dependencies:
  lint_hard: ^5.0.0
  money2: ^5.1.0
  test: ^1.6.7
