name: scope
version: 3.0.0
homepage: https://github.com/noojee/scope
documentation: https://scope.noojee.dev
publish_to: https://beta.onepub.dev/api/jbbxpsdavu/
description: A Dependency injection (Inversion of Control) library. Supports nested Scopes and multiple values of the same type.
repository: https://github.com/noojee/scope
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  meta: ^1.1.7
dev_dependencies: 
  lint_hard: ^1.0.0
  money2: ^2.3.0
  test: ^1.6.7
