name: scope
version: 4.0.1
homepage: https://github.com/noojee/scope
documentation: https://scope.noojee.dev
description: A Dependency injection (Inversion of Control) library. Supports nested Scopes and multiple values of the same type.
repository: https://github.com/noojee/scope
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  meta: ^1.1.7
dev_dependencies: 
  lint_hard: ^4.0.0
  money2: ^3.4.1
  test: ^1.6.7
